services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:1337
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - /var/lib/mysql/
    networks:
      - inception
    restart: always

networks:
  inception:
