services:
  nginx:
    build: ./requirements/nginx/
    image: nginx:1337
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:1337
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:1337
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - /var/lib/mysql/
    networks:
      - inception
    restart: always

networks:
  inception:

volumes:
  wordpress:
