version: '3.5'

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - .env

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /workspaces/inception/srcs/requirements/mariadb
      o: bind 

networks:
  inception:
    name: inception
