services:
  nginx:
    build: ./requirements/nginx/
    image: nginx:1337
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:1337
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - /var/lib/mysql/
    networks:
      - inception
    restart: always

networks:
  inception:
